title: CNC Tools Documentation
description: Documentation for the CNC Tools Next.js application
remote_theme: just-the-docs/just-the-docs

url: https://deejpotter.github.io/cnc-tools
baseurl: "/cnc-tools"

# Add plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Enable search
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable copy code button
enable_copy_code_button: true

# Navigation
nav_external_links:
  - title: CNC Tools on GitHub
    url: https://github.com/deejpotter/cnc-tools
    hide_icon: false

# Footer content
footer_content: "Copyright &copy; 2025 Daniel Potter. Distributed under an MIT license."
